"""empty message

Revision ID: 185b5f308ae7
Revises: b70b35cfc346
Create Date: 2023-06-18 00:30:37.434218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185b5f308ae7'
down_revision = 'b70b35cfc346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entries',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mood', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('entry_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_entries')
    # ### end Alembic commands ###
